Update target and CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,7 +29,7 @@ jobs:
     
     - name: Install Rust target for wasm
       run: |
-        rustup target add wasm32-wasi
+        rustup target add wasm32-wasip1
         
     - name: Install WasmEdge
       run: |
@@ -38,8 +38,8 @@ jobs:
     
     - name: microservice
       run: |
-        cargo build --target wasm32-wasi --release
-        wasmedgec target/wasm32-wasi/release/sales_tax_rate_lookup.wasm sales_tax_rate_lookup.wasm
+        cargo build --target wasm32-wasip1 --release
+        wasmedgec target/wasm32-wasip1/release/sales_tax_rate_lookup.wasm sales_tax_rate_lookup.wasm
         nohup wasmedge sales_tax_rate_lookup.wasm &
         echo $! > wasmedge.pid
         sleep 15
@@ -51,9 +51,17 @@ jobs:
           echo -e "Execution Fail!"
           exit 1
         fi
-        resp=$(curl http://localhost:8001/find_rate -X POST -d "12345")
+        resp=$(curl http://localhost:8001/find_rate -X POST -d "89102")
         echo "$resp"
-        if [[ $resp == "0.08" ]]; then
+        if [[ $resp == "0.08375" ]]; then
+          echo -e "Execution Success!"
+        else
+          echo -e "Execution Fail!"
+          exit 1
+        fi
+        resp=$(curl --include --silent http://localhost:8001/find_rate -X POST -d "12345" | head -1 | awk '{print $2 }')
+        echo "$resp"
+        if [[ $resp == "404" ]]; then
           echo -e "Execution Success!"
         else
           echo -e "Execution Fail!"
